In [1]:
import numpy as np
import pandas as pd



In [4]:
#help(pd.Series)

In [5]:
myindex = ['USA','Canada','Mexico']
mydata = [1776,1867,1821]

In [9]:
myser = pd.Series(data=mydata,index=myindex)

In [10]:
myser

USA       1776
Canada    1867
Mexico    1821
dtype: int64

In [8]:
type(myser)

pandas.core.series.Series

In [11]:
myser[0]  #number index given default

1776

In [12]:
myser['USA']  #Labeled index 

1776

In [13]:
ages ={'Sam':5,'Frank':10,'Spike':7}

In [14]:
pd.Series(ages)   #keys are index, values are data

Sam       5
Frank    10
Spike     7
dtype: int64

In [15]:
expenses = pd.Series({'Andrew':200,'Bob':150,'Claire':450})
expenses['Bob']

150

In [16]:
expenses.keys()

Index(['Andrew', 'Bob', 'Claire'], dtype='object')

In [17]:
np.array([1,2])*2

array([2, 4])

In [18]:
expenses*2

Andrew    400
Bob       300
Claire    900
dtype: int64

In [22]:
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [23]:
myindex = ['CA','NY','AZ','TX']

In [24]:
mycolumns=['Jan','Feb','Mar']

In [28]:
df = pd.DataFrame(mydata,myindex,mycolumns)

In [29]:
df

Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

In [30]:
pwd

'C:\\Users\\admin\\Zahire_vs_code\\JUPYTER'

In [31]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 0A42-6144

 Directory of C:\Users\admin\Zahire_vs_code\JUPYTER

06/05/2021  11:45 PM    <DIR>          .
06/05/2021  11:45 PM    <DIR>          ..
06/05/2021  10:54 PM    <DIR>          .ipynb_checkpoints
06/04/2021  12:23 AM            40,903 numpy_array.ipynb
06/05/2021  11:45 PM             7,872 Pandas_Ex.ipynb
               2 File(s)         48,775 bytes
               3 Dir(s)  165,258,035,200 bytes free


In [2]:
df=pd.read_csv('titanic.csv')

In [23]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [1]:
import numpy as np

In [3]:
v = np.array([1,1,2,2,3,3,3,3])

In [4]:
np.mean(v)

2.25

In [5]:
np.median(v)

2.5

In [6]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])

In [7]:
np.linalg.solve(a,b)

array([2., 3.])

In [8]:
import pandas as pd

In [9]:
pd.Series([10, 88, 3, 4, 5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [10]:
ser = pd.Series([10, 88, 3, 4, 5])

In [11]:
ser

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [12]:
type(ser)

pandas.core.series.Series

In [13]:
ser.dtype

dtype('int64')

In [14]:
ser.size

5

In [15]:
ser.values

array([10, 88,  3,  4,  5], dtype=int64)

In [16]:
for i in ser.values:
    print(i)

10
88
3
4
5


In [24]:
labels = ["a","b","c"]
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {"a":10,"b":20,"c":30}

In [25]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [26]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [27]:
d["a"]

10

In [28]:
ser1 = pd.Series([1,2,3,4], index = ["US","Germany","USSR","Japan"])
ser1

US         1
Germany    2
USSR       3
Japan      4
dtype: int64

In [29]:
ser1["US"]

1

In [30]:
ser1[0]

1

In [31]:
ser2 = pd.Series([1,2,5,4], index = ["US","Germany","Italy","Japan"])
ser2
ser3 = pd.Series(data = labels)
ser3
ser3[0]

'a'

In [32]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
US         2.0
USSR       NaN
dtype: float64

In [34]:
ser1.add(ser2,fill_value=0)

Germany    4.0
Italy      5.0
Japan      8.0
US         2.0
USSR       3.0
dtype: float64

In [35]:
panser = pd.Series([121, 200, 150, 99], index =["ali","veli","ayşe","nur"])
panser

ali     121
veli    200
ayşe    150
nur      99
dtype: int64

In [36]:
panser[0:3]

ali     121
veli    200
ayşe    150
dtype: int64

In [37]:
panser["ali":"nur"]

ali     121
veli    200
ayşe    150
nur      99
dtype: int64

In [38]:
panser.items

<bound method Series.items of ali     121
veli    200
ayşe    150
nur      99
dtype: int64>

In [39]:
"mehmet" in panser

False

In [40]:
"ali" in panser

True

In [41]:
121 in panser

False

In [42]:
121 in panser.values

True

In [43]:
panser>130

ali     False
veli     True
ayşe     True
nur     False
dtype: bool

In [44]:
datam = np.array([1,2,39,67,90])

In [47]:
df =pd.DataFrame(datam, columns = ["Columns"])

In [48]:
df

Columns
0        1
1        2
2       39
3       67
4       90

In [50]:
panser.head(1)

ali    121
dtype: int64

In [53]:
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
s3 = np.random.randint(10, size=5)

In [54]:
s1,s2,s3

(array([2, 8, 8, 8, 0]), array([5, 9, 2, 5, 0]), array([1, 5, 0, 3, 0]))

In [55]:
mydict = {"var1":s1, "var2":s2, "var3":s3}
mydict

{'var1': array([2, 8, 8, 8, 0]),
 'var2': array([5, 9, 2, 5, 0]),
 'var3': array([1, 5, 0, 3, 0])}

In [56]:
df = pd.DataFrame(mydict)

In [57]:
df

var1  var2  var3
0     2     5     1
1     8     9     5
2     8     2     0
3     8     5     3
4     0     0     0

In [62]:
df1=pd.read_csv("ornekcsv.csv", delimiter=";")

In [63]:
df1[1:3]

a    b    c
1  78   12  2.0
2  78  324  3.0

In [64]:
df1.index

RangeIndex(start=0, stop=13, step=1)

In [4]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [10]:
df=df.set_index("Embarked")
df.head()

PassengerId  Survived  Pclass  \
Embarked                                  
S                   1         0       3   
C                   2         1       1   
S                   3         1       3   
S                   4         1       1   
S                   5         0       3   

                                                       Name     Sex   Age  \
Embarked                                                                    
S                                   Braund, Mr. Owen Harris    male  22.0   
C         Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
S                                    Heikkinen, Miss. Laina  female  26.0   
S              Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
S                                  Allen, Mr. William Henry    male  35.0   

          SibSp  Parch            Ticket     Fare Cabin  
Embarked                                                 
S             1      0         A/5 21171   7.2500   NaN  
C             1      0          PC 17599  71.2833   C85  
S             0      0  STON/O2. 3101282   7.9250   NaN  
S             1      0            113803  53.1000  C123  
S             0      0            373450   8.0500   NaN

In [13]:
one_row=df.iloc[0]

In [16]:
df = df.append(one_row).tail()

In [17]:
df.tail()

PassengerId  Survived  Pclass  \
Embarked                                  
S                 888         1       1   
S                 889         0       3   
C                 890         1       1   
Q                 891         0       3   
S                   1         0       3   

                                              Name     Sex   Age  SibSp  \
Embarked                                                                  
S                     Graham, Miss. Margaret Edith  female  19.0      0   
S         Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
C                            Behr, Mr. Karl Howell    male  26.0      0   
Q                              Dooley, Mr. Patrick    male  32.0      0   
S                          Braund, Mr. Owen Harris    male  22.0      1   

          Parch      Ticket   Fare Cabin  
Embarked                                  
S             0      112053  30.00   B42  
S             2  W./C. 6607  23.45   NaN  
C             0      111369  30.00  C148  
Q             0      370376   7.75   NaN  
S             0   A/5 21171   7.25   NaN

In [18]:
df.head()

PassengerId  Survived  Pclass  \
Embarked                                  
S                 888         1       1   
S                 889         0       3   
C                 890         1       1   
Q                 891         0       3   
S                   1         0       3   

                                              Name     Sex   Age  SibSp  \
Embarked                                                                  
S                     Graham, Miss. Margaret Edith  female  19.0      0   
S         Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
C                            Behr, Mr. Karl Howell    male  26.0      0   
Q                              Dooley, Mr. Patrick    male  32.0      0   
S                          Braund, Mr. Owen Harris    male  22.0      1   

          Parch      Ticket   Fare Cabin  
Embarked                                  
S             0      112053  30.00   B42  
S             2  W./C. 6607  23.45   NaN  
C             0      111369  30.00  C148  
Q             0      370376   7.75   NaN  
S             0   A/5 21171   7.25   NaN

In [24]:
bool_series = df['Sex']=='male'

In [31]:
df[(df['Sex']=='male') & (df['Survived']==0)]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
881          882         0       3              Markun, Mr. Johann  male   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
881  33.0      0      0            349257   7.8958   NaN        S  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
890  32.0      0      0            370376   7.7500   NaN        Q  

[468 rows x 12 columns]

PassengerId  Survived  Pclass  \
Embarked                                  
S                 888         1       1   
S                 889         0       3   
C                 890         1       1   
Q                 891         0       3   
S                   1         0       3   

                                              Name     Sex   Age  SibSp  \
Embarked                                                                  
S                     Graham, Miss. Margaret Edith  female  19.0      0   
S         Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
C                            Behr, Mr. Karl Howell    male  26.0      0   
Q                              Dooley, Mr. Patrick    male  32.0      0   
S                          Braund, Mr. Owen Harris    male  22.0      1   

          Parch      Ticket   Fare Cabin  
Embarked                                  
S             0      112053  30.00   B42  
S             2  W./C. 6607  23.45   NaN  
C             0      111369  30.00  C148  
Q             0      370376   7.75   NaN  
S             0   A/5 21171   7.25   NaN

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [38]:
options= [1,2]
list(df['Pclass'].isin(options)).count(True)

400

In [39]:
df.reset_index()

index  PassengerId  Survived  Pclass  \
0        0            1         0       3   
1        1            2         1       1   
2        2            3         1       3   
3        3            4         1       1   
4        4            5         0       3   
..     ...          ...       ...     ...   
886    886          887         0       2   
887    887          888         1       1   
888    888          889         0       3   
889    889          890         1       1   
890    890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 13 columns]

In [40]:
def name(s):
    return s.split(',')[0]

In [42]:
name('Braund, Mr. Owen Harris')

'Braund'

In [43]:
df['First_Name']=df['Name'].apply(name)

In [44]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked First_Name  
0      0         A/5 21171   7.2500   NaN        S     Braund  
1      0          PC 17599  71.2833   C85        C    Cumings  
2      0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen  
3      0            113803  53.1000  C123        S   Futrelle  
4      0            373450   8.0500   NaN        S      Allen

In [46]:
df.drop('First_Name',axis=1)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [47]:
df['Name'].apply(lambda s: s.split(",")[0])

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...    
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: Name, Length: 891, dtype: object

In [51]:
df.sort_values(['Pclass','Survived'])

PassengerId  Survived  Pclass                                   Name  \
6              7         0       1                McCarthy, Mr. Timothy J   
27            28         0       1         Fortune, Mr. Charles Alexander   
30            31         0       1               Uruchurtu, Don. Manuel E   
34            35         0       1                Meyer, Mr. Edgar Joseph   
35            36         0       1         Holverson, Mr. Alexander Oskar   
..           ...       ...     ...                                    ...   
838          839         1       3                        Chip, Mr. Chang   
855          856         1       3             Aks, Mrs. Sam (Leah Rosen)   
858          859         1       3  Baclini, Mrs. Solomon (Latifa Qurban)   
869          870         1       3        Johnson, Master. Harold Theodor   
875          876         1       3       Najib, Miss. Adele Kiamie "Jane"   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  \
6      male  54.0      0      0     17463   51.8625          E46        S   
27     male  19.0      3      2     19950  263.0000  C23 C25 C27        S   
30     male  40.0      0      0  PC 17601   27.7208          NaN        C   
34     male  28.0      1      0  PC 17604   82.1708          NaN        C   
35     male  42.0      1      0    113789   52.0000          NaN        S   
..      ...   ...    ...    ...       ...       ...          ...      ...   
838    male  32.0      0      0      1601   56.4958          NaN        S   
855  female  18.0      0      1    392091    9.3500          NaN        S   
858  female  24.0      0      3      2666   19.2583          NaN        C   
869    male   4.0      1      1    347742   11.1333          NaN        S   
875  female  15.0      0      0      2667    7.2250          NaN        C   

    First_Name  
6     McCarthy  
27     Fortune  
30   Uruchurtu  
34       Meyer  
35   Holverson  
..         ...  
838       Chip  
855        Aks  
858    Baclini  
869    Johnson  
875      Najib  

[891 rows x 13 columns]

In [54]:
df['Fare'].idxmax()

258

In [55]:
df.iloc[258]

PassengerId                 259
Survived                      1
Pclass                        1
Name           Ward, Miss. Anna
Sex                      female
Age                        35.0
SibSp                         0
Parch                         0
Ticket                 PC 17755
Fare                   512.3292
Cabin                       NaN
Embarked                      C
First_Name                 Ward
Name: 258, dtype: object

In [56]:
df.corr()

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443   
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549500  
Age          0.096067  
SibSp        0.159651  
Parch        0.216225  
Fare         1.000000

In [57]:
df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [59]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked First_Name  
0        0         A/5 21171   7.2500   NaN        S     Braund  
1        0          PC 17599  71.2833   C85        C    Cumings  
2        0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen  
3        0            113803  53.1000  C123        S   Futrelle  
4        0            373450   8.0500   NaN        S      Allen  
..     ...               ...      ...   ...      ...        ...  
886      0            211536  13.0000   NaN        S   Montvila  
887      0            112053  30.0000   B42        S     Graham  
888      2        W./C. 6607  23.4500   NaN        S   Johnston  
889      0            111369  30.0000  C148        C       Behr  
890      0            370376   7.7500   NaN        Q     Dooley  

[891 rows x 13 columns]

In [60]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [61]:
df.sample(frac=0.1)

PassengerId  Survived  Pclass                                       Name  \
364          365         0       3                        O'Brien, Mr. Thomas   
751          752         1       3                        Moor, Master. Meier   
436          437         0       3       Ford, Miss. Doolina Margaret "Daisy"   
736          737         0       3    Ford, Mrs. Edward (Margaret Ann Watson)   
220          221         1       3             Sunderland, Mr. Victor Francis   
..           ...       ...     ...                                        ...   
257          258         1       1                       Cherry, Miss. Gladys   
632          633         1       1                  Stahelin-Maeglin, Dr. Max   
841          842         0       2                   Mudd, Mr. Thomas Charles   
236          237         0       2                          Hold, Mr. Stephen   
763          764         1       1  Carter, Mrs. William Ernest (Lucile Polk)   

        Sex   Age  SibSp  Parch           Ticket     Fare    Cabin Embarked  \
364    male   NaN      1      0           370365   15.500      NaN        Q   
751    male   6.0      0      1           392096   12.475     E121        S   
436  female  21.0      2      2       W./C. 6608   34.375      NaN        S   
736  female  48.0      1      3       W./C. 6608   34.375      NaN        S   
220    male  16.0      0      0  SOTON/OQ 392089    8.050      NaN        S   
..      ...   ...    ...    ...              ...      ...      ...      ...   
257  female  30.0      0      0           110152   86.500      B77        S   
632    male  32.0      0      0            13214   30.500      B50        C   
841    male  16.0      0      0      S.O./P.P. 3   10.500      NaN        S   
236    male  44.0      1      0            26707   26.000      NaN        S   
763  female  36.0      1      2           113760  120.000  B96 B98        S   

           First_Name  
364           O'Brien  
751              Moor  
436              Ford  
736              Ford  
220        Sunderland  
..                ...  
257            Cherry  
632  Stahelin-Maeglin  
841              Mudd  
236              Hold  
763            Carter  

[89 rows x 13 columns]

In [78]:
def str(s1,s2):
    st=s1.index(s2[0])#how many times shift
    return all(True if s2[i]==s1[(i+st)%len(s1)] else False for i in range(len(s2)))
str('abcde','deabc')


True

In [79]:
df.isnull()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  First_Name  
0    False   True     False       False  
1    False  False     False       False  
2    False   True     False       False  
3    False  False     False       False  
4    False   True     False       False  
..     ...    ...       ...         ...  
886  False   True     False       False  
887  False  False     False       False  
888  False   True     False       False  
889  False  False     False       False  
890  False   True     False       False  

[891 rows x 13 columns]

In [80]:
df.notnull()

PassengerId  Survived  Pclass  Name   Sex    Age  SibSp  Parch  Ticket  \
0           True      True    True  True  True   True   True   True    True   
1           True      True    True  True  True   True   True   True    True   
2           True      True    True  True  True   True   True   True    True   
3           True      True    True  True  True   True   True   True    True   
4           True      True    True  True  True   True   True   True    True   
..           ...       ...     ...   ...   ...    ...    ...    ...     ...   
886         True      True    True  True  True   True   True   True    True   
887         True      True    True  True  True   True   True   True    True   
888         True      True    True  True  True  False   True   True    True   
889         True      True    True  True  True   True   True   True    True   
890         True      True    True  True  True   True   True   True    True   

     Fare  Cabin  Embarked  First_Name  
0    True  False      True        True  
1    True   True      True        True  
2    True  False      True        True  
3    True   True      True        True  
4    True  False      True        True  
..    ...    ...       ...         ...  
886  True  False      True        True  
887  True   True      True        True  
888  True  False      True        True  
889  True   True      True        True  
890  True  False      True        True  

[891 rows x 13 columns]

In [86]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked First_Name  
0        0         A/5 21171   7.2500   NaN        S     Braund  
1        0          PC 17599  71.2833   C85        C    Cumings  
2        0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen  
3        0            113803  53.1000  C123        S   Futrelle  
4        0            373450   8.0500   NaN        S      Allen  
..     ...               ...      ...   ...      ...        ...  
886      0            211536  13.0000   NaN        S   Montvila  
887      0            112053  30.0000   B42        S     Graham  
888      2        W./C. 6607  23.4500   NaN        S   Johnston  
889      0            111369  30.0000  C148        C       Behr  
890      0            370376   7.7500   NaN        Q     Dooley  

[891 rows x 13 columns]

In [99]:
def my_list(lis):
    mul,new=1,[]
    for i in lis:
        mul*=i
    for i in lis:
        try:
            new.append(mul//i)
        except:
              print("Zero Division Error") 
              break  
    if new:
        return new
my_list([3, 2, 1])

[2, 3, 6]

In [108]:
def my_list(lis):
    new=[]
    for i in lis:
        mul=1
        for j in lis:
            if i!=j:
                mul*=j
        new.append(mul)
    return new  
my_list([1, 2, 3, 4, 5])

[120, 60, 40, 30, 24]

In [115]:
def my_list(lis):
    mul=1
    for i in lis:  
         new=[mul*=j for j in lis if i!=j ]
  
        
    return new  
my_list([1, 2, 3, 4, 5])

SyntaxError: invalid syntax (<ipython-input-115-feab572abbca>, line 4)

In [4]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [31]:
sex_class=df.groupby(['Sex','Pclass']).mean()
sex_class.sort_index(level='Pclass',ascending=False)

PassengerId  Survived        Age     SibSp     Parch  \
Sex    Pclass                                                         
male   3        455.515850  0.135447  26.507589  0.498559  0.224784   
female 3        399.729167  0.500000  21.750000  0.895833  0.798611   
male   2        447.962963  0.157407  30.740707  0.342593  0.222222   
female 2        443.105263  0.921053  28.722973  0.486842  0.605263   
male   1        455.729508  0.368852  41.281386  0.311475  0.278689   
female 1        469.212766  0.968085  34.611765  0.553191  0.457447   

                     Fare  
Sex    Pclass              
male   3        12.661633  
female 3        16.118810  
male   2        19.741782  
female 2        21.970121  
male   1        67.226127  
female 1       106.125798

In [20]:
sex_class.xs(key=1,level='Pclass')

PassengerId  Survived        Age     SibSp     Parch        Fare
Sex                                                                     
female   469.212766  0.968085  34.611765  0.553191  0.457447  106.125798
male     455.729508  0.368852  41.281386  0.311475  0.278689   67.226127

In [29]:
df[df['Pclass'].isin([1,2])].groupby(['Pclass','Sex'])[['Fare','Age']].mean()


Fare        Age
Pclass Sex                          
1      female  106.125798  34.611765
       male     67.226127  41.281386
2      female   21.970121  28.722973
       male     19.741782  30.740707

In [32]:
sex_class

PassengerId  Survived        Age     SibSp     Parch  \
Sex    Pclass                                                         
female 1        469.212766  0.968085  34.611765  0.553191  0.457447   
       2        443.105263  0.921053  28.722973  0.486842  0.605263   
       3        399.729167  0.500000  21.750000  0.895833  0.798611   
male   1        455.729508  0.368852  41.281386  0.311475  0.278689   
       2        447.962963  0.157407  30.740707  0.342593  0.222222   
       3        455.515850  0.135447  26.507589  0.498559  0.224784   

                     Fare  
Sex    Pclass              
female 1       106.125798  
       2        21.970121  
       3        16.118810  
male   1        67.226127  
       2        19.741782  
       3        12.661633

In [33]:
sex_class.sort_values('Age')

PassengerId  Survived        Age     SibSp     Parch  \
Sex    Pclass                                                         
female 3        399.729167  0.500000  21.750000  0.895833  0.798611   
male   3        455.515850  0.135447  26.507589  0.498559  0.224784   
female 2        443.105263  0.921053  28.722973  0.486842  0.605263   
male   2        447.962963  0.157407  30.740707  0.342593  0.222222   
female 1        469.212766  0.968085  34.611765  0.553191  0.457447   
male   1        455.729508  0.368852  41.281386  0.311475  0.278689   

                     Fare  
Sex    Pclass              
female 3        16.118810  
male   3        12.661633  
female 2        21.970121  
male   2        19.741782  
female 1       106.125798  
male   1        67.226127

In [43]:
df.agg(['mean','std'])

PassengerId  Survived    Pclass        Age     SibSp     Parch  \
mean   446.000000  0.383838  2.308642  29.699118  0.523008  0.381594   
std    257.353842  0.486592  0.836071  14.526497  1.102743  0.806057   

           Fare  
mean  32.204208  
std   49.693429

In [68]:

one=pd.DataFrame({'A':['A0','A1','A3','A4'],'B':['B0','B1','B3','B4']})
two=pd.DataFrame({'C':['C0','C1','C3','C4'],'D':['D0','D1','D3','D4']})              
one
two

C   D
0  C0  D0
1  C1  D1
2  C3  D3
3  C4  D4

In [69]:
one

A   B
0  A0  B0
1  A1  B1
2  A3  B3
3  A4  B4

In [72]:
pd.concat([one,two],axis=1)


A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A3  B3  C3  D3
3  A4  B4  C4  D4

In [76]:
one_2=one.transpose()
two_2=two.transpose()
pd.concat([one_2,two_2],axis=0)

0   1   2   3
A  A0  A1  A3  A4
B  B0  B1  B3  B4
C  C0  C1  C3  C4
D  D0  D1  D3  D4

In [78]:
import numpy;print(numpy.reshape(numpy.array(list(map(int,input().split()))),(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
arr=np.arange(10)

In [80]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [83]:
datam = [1,2,3,4,5,6,7,8]

In [92]:
pd.DataFrame(datam,columns=['sayılar'])

sayılar
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8

In [86]:
m = np.arange(1,10).reshape((3,3))

In [87]:
df=pd.DataFrame(m,columns=['var1','var2','var3'])

In [88]:
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [89]:
df.sample()

var1  var2  var3
1     4     5     6

In [90]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [93]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
s1 = np.random.randint(10, size =5)
s2 = np.random.randint(10, size =5)
s3 = np.random.randint(10, size =5)
s3

array([7, 6, 0, 7, 5])

In [95]:
mydict = {'var1':s1,'var2':s2,'var3':s3}

In [96]:
mydict

{'var1': array([3, 3, 3, 0, 5]),
 'var2': array([3, 6, 9, 2, 9]),
 'var3': array([7, 6, 0, 7, 5])}

In [97]:
df1 = pd.DataFrame(mydict)
df1

var1  var2  var3
0     3     3     7
1     3     6     6
2     3     9     0
3     0     2     7
4     5     9     5

In [100]:
df3 = pd.read_csv('ornek.csv')

In [101]:
df3.head()

a   b     c
0  10  12   3.0
1  11  33  34.0
2  44  51   NaN
3  10  12   4.0
4  11  33  35.0

In [102]:
df3.shape

(15, 3)

In [103]:
df1[1:4]

var1  var2  var3
1     3     6     6
2     3     9     0
3     0     2     7

In [106]:
df1.index=['a','b','c','d','e']

In [107]:
df1

var1  var2  var3
a     3     3     7
b     3     6     6
c     3     9     0
d     0     2     7
e     5     9     5

In [113]:
np.random.seed(101)

In [137]:
df4 = pd.DataFrame(np.random.randn(5,4),index='A B C D E'.split(),columns="W X Y Z".split())
df4

W         X         Y         Z
A -0.497104 -0.754070 -0.943406  0.484752
B -0.116773  1.901755  0.238127  1.996652
C -0.993263  0.196800 -1.136645  0.000366
D  1.025984 -0.156598 -0.031579  0.649826
E  2.154846 -0.610259 -0.755325 -0.346419

In [111]:
df4.mean()

0    0.343858
1    0.453764
2    0.452287
3    0.431871
dtype: float64

In [115]:
df4[["W","Z"]]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [116]:
df4['A':'C']

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [117]:
df4["yeni"] = df4['W']+df4['Z']

In [118]:
df4

W         X         Y         Z      yeni
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [121]:
df4.drop('yeni',axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [122]:
df4

W         X         Y         Z      yeni
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [124]:
df4.drop('A',axis=0)

W         X         Y         Z      yeni
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [125]:
m = np.random.randint(1,30, size = (10,3))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df4

var1  var2  var3
0     8    11    21
1    25     8     7
2    15    10    21
3    19    24     8
4     8    16    13
5     1    21    11
6    13    18    25
7    12    20    16
8     2    25     5
9    29    20    19

In [128]:
df4.iloc[1:4]

var1  var2  var3
1    25     8     7
2    15    10    21
3    19    24     8

In [129]:
df4.index= "a b c d e f g h i j".split()

In [130]:
df4

var1  var2  var3
a     8    11    21
b    25     8     7
c    15    10    21
d    19    24     8
e     8    16    13
f     1    21    11
g    13    18    25
h    12    20    16
i     2    25     5
j    29    20    19

In [136]:
df4.loc["a":"f"][["var1"]]

var1
a     8
b    25
c    15
d    19
e     8
f     1

In [138]:
df4

W         X         Y         Z
A -0.497104 -0.754070 -0.943406  0.484752
B -0.116773  1.901755  0.238127  1.996652
C -0.993263  0.196800 -1.136645  0.000366
D  1.025984 -0.156598 -0.031579  0.649826
E  2.154846 -0.610259 -0.755325 -0.346419

In [140]:
df4.iloc[[3]]

W         X         Y         Z
D  1.025984 -0.156598 -0.031579  0.649826

In [141]:
df4.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [150]:
df4.iloc[[0,1],[0]]



W
A -0.497104
B -0.116773

In [151]:
df4>0

W      X      Y      Z
A  False  False  False   True
B  False   True   True   True
C  False   True  False   True
D   True  False  False   True
E   True  False  False  False

In [155]:
df4

W         X         Y         Z
A -0.497104 -0.754070 -0.943406  0.484752
B -0.116773  1.901755  0.238127  1.996652
C -0.993263  0.196800 -1.136645  0.000366
D  1.025984 -0.156598 -0.031579  0.649826
E  2.154846 -0.610259 -0.755325 -0.346419

In [154]:
df4[df4["W"]>0][["Y", "Z"]]

Y         Z
D -0.031579  0.649826
E -0.755325 -0.346419

fadmk



In [156]:
df4.set_index('Z')

W         X         Y
Z                                      
 0.484752 -0.497104 -0.754070 -0.943406
 1.996652 -0.116773  1.901755  0.238127
 0.000366 -0.993263  0.196800 -1.136645
 0.649826  1.025984 -0.156598 -0.031579
-0.346419  2.154846 -0.610259 -0.755325

In [158]:
df4.reset_index()

index         W         X         Y         Z
0     A -0.497104 -0.754070 -0.943406  0.484752
1     B -0.116773  1.901755  0.238127  1.996652
2     C -0.993263  0.196800 -1.136645  0.000366
3     D  1.025984 -0.156598 -0.031579  0.649826
4     E  2.154846 -0.610259 -0.755325 -0.346419

In [160]:
df4.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [161]:
df4

W         X         Y         Z
A -0.497104 -0.754070 -0.943406  0.484752
B -0.116773  1.901755  0.238127  1.996652
C -0.993263  0.196800 -1.136645  0.000366
D  1.025984 -0.156598 -0.031579  0.649826
E  2.154846 -0.610259 -0.755325 -0.346419

In [162]:
new_index = "CA NY WY OR CO".split()
new_index

['CA', 'NY', 'WY', 'OR', 'CO']

In [163]:
df4['States'] = new_index
df4

W         X         Y         Z States
A -0.497104 -0.754070 -0.943406  0.484752     CA
B -0.116773  1.901755  0.238127  1.996652     NY
C -0.993263  0.196800 -1.136645  0.000366     WY
D  1.025984 -0.156598 -0.031579  0.649826     OR
E  2.154846 -0.610259 -0.755325 -0.346419     CO

In [165]:
df4.set_index("States",inplace=True)

In [166]:
df4

W         X         Y         Z
States                                        
CA     -0.497104 -0.754070 -0.943406  0.484752
NY     -0.116773  1.901755  0.238127  1.996652
WY     -0.993263  0.196800 -1.136645  0.000366
OR      1.025984 -0.156598 -0.031579  0.649826
CO      2.154846 -0.610259 -0.755325 -0.346419

In [168]:
outside = ['M1', 'M1', 'M1', 'M2', 'M2', 'M2']
inside = [1, 2, 3, 1, 2, 3]
multi_index = list(zip(outside, inside))
multi_index
hier_index=pd.MultiIndex.from_tuples(multi_index)

In [173]:
df5 = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])

In [174]:
df5

A         B
M1 1  0.992573  1.192241
   2 -1.046780  1.292765
   3 -1.467514 -0.494095
M2 1 -0.162535  0.485809
   2  0.392489  0.221491
   3 -0.855196  1.541990

In [178]:
df5.loc['M1']

A         B
1  0.992573  1.192241
2 -1.046780  1.292765
3 -1.467514 -0.494095

In [177]:
df5.xs('M1')

A         B
1  0.992573  1.192241
2 -1.046780  1.292765
3 -1.467514 -0.494095

In [179]:
df5.xs(("M1",1))

A    0.992573
B    1.192241
Name: (M1, 1), dtype: float64

In [2]:
import seaborn as sns

In [4]:
df = sns.load_dataset("planets")

In [182]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [183]:
df.shape

(1035, 6)

In [184]:
df.tail()

method  number  orbital_period  mass  distance  year
1030  Transit       1        3.941507   NaN     172.0  2006
1031  Transit       1        2.615864   NaN     148.0  2007
1032  Transit       1        3.191524   NaN     174.0  2007
1033  Transit       1        4.125083   NaN     293.0  2008
1034  Transit       1        4.187757   NaN     260.0  2008

In [185]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [186]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   method          1035 non-null   object 
 1   number          1035 non-null   int64  
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB


In [187]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [188]:
df.iloc[1:5,2:4]

orbital_period   mass
1         874.774   2.21
2         763.000   2.60
3         326.030  19.40
4         516.220  10.50

In [189]:
df.drop('number',axis=1)

method  orbital_period   mass  distance  year
0     Radial Velocity      269.300000   7.10     77.40  2006
1     Radial Velocity      874.774000   2.21     56.95  2008
2     Radial Velocity      763.000000   2.60     19.84  2011
3     Radial Velocity      326.030000  19.40    110.62  2007
4     Radial Velocity      516.220000  10.50    119.47  2009
...               ...             ...    ...       ...   ...
1030          Transit        3.941507    NaN    172.00  2006
1031          Transit        2.615864    NaN    148.00  2007
1032          Transit        3.191524    NaN    174.00  2007
1033          Transit        4.125083    NaN    293.00  2008
1034          Transit        4.187757    NaN    260.00  2008

[1035 rows x 5 columns]

In [192]:
df[(df['mass']>3)|(df['distance']>180)].shape

(322, 6)

In [199]:
def missing(lis):
    new=[i for i in set(lis)  if i>0 ]
    return [min(new)+1+i for i in range(len(new)) if min(new)+1+i not in new][0]
   # for i in range(len(new)):
    #    if min(new)+1+i not in new:
     #       return min(new)+1+i
                   
missing([0,1,2])   

3

In [2]:
from datetime  import datetime

In [3]:
myyear = 2015
mymonth = 1
myday = 1
myhour = 2
mymin = 30
mysec =15

In [4]:
mydatetime = datetime(myyear,mymonth,myday)
mydatetime

datetime.datetime(2015, 1, 1, 0, 0)

In [5]:
mydatetime = datetime(myyear,mymonth,myday,myhour,mymin,mysec)

In [6]:
mydatetime

datetime.datetime(2015, 1, 1, 2, 30, 15)

In [7]:
myser = pd.Series(['Nov 3, 1990','2000-01-01-',None])

In [8]:
myser

0    Nov 3, 1990
1    2000-01-01-
2           None
dtype: object

In [10]:
timeser = pd.to_datetime(myser)

In [11]:
timeser

0   1990-11-03
1   2000-01-01
2          NaT
dtype: datetime64[ns]

In [12]:
timeser[0].year

1990

In [13]:
style_date ='12--Dec--2000'
pd.to_datetime(style_date,format='%d--%b--%Y')

Timestamp('2000-12-12 00:00:00')

In [14]:
df.head()

NameError: name 'df' is not defined

In [5]:
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [7]:
df.shape

(1035, 6)

In [9]:
df['orbital_period'].idxmin()

945

In [14]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [13]:
df.isnull().sum()

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [15]:
df.dropna(how='all')

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [16]:
df.corr()

number  orbital_period      mass  distance      year
number          1.000000       -0.012570 -0.241429 -0.033638  0.147849
orbital_period -0.012570        1.000000  0.173725 -0.034365 -0.032333
mass           -0.241429        0.173725  1.000000  0.274082 -0.123787
distance       -0.033638       -0.034365  0.274082  1.000000  0.178922
year            0.147849       -0.032333 -0.123787  0.178922  1.000000

In [18]:
df["method"].value_counts()

Radial Velocity                  553
Transit                          397
Imaging                           38
Microlensing                      23
Eclipse Timing Variations          9
Pulsar Timing                      5
Transit Timing Variations          4
Orbital Brightness Modulation      3
Astrometry                         2
Pulsation Timing Variations        1
Name: method, dtype: int64

In [21]:
df.groupby('method')[['orbital_period']].mean()

orbital_period
method                                       
Astrometry                         631.180000
Eclipse Timing Variations         4751.644444
Imaging                         118247.737500
Microlensing                      3153.571429
Orbital Brightness Modulation        0.709307
Pulsar Timing                     7343.021201
Pulsation Timing Variations       1170.000000
Radial Velocity                    823.354680
Transit                             21.102073
Transit Timing Variations           79.783500

In [24]:
df.year.unique()

array([2006, 2008, 2011, 2007, 2009, 2002, 1996, 2010, 2001, 1995, 2004,
       2012, 2013, 2005, 2000, 2003, 1997, 1999, 2014, 1998, 1989, 1992,
       1994], dtype=int64)

In [26]:
df.head(3)

method  number  orbital_period  mass  distance  year
0  Radial Velocity       1         269.300  7.10     77.40  2006
1  Radial Velocity       1         874.774  2.21     56.95  2008
2  Radial Velocity       1         763.000  2.60     19.84  2011

In [27]:
data = {'Company':['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
       'Person':['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
       'Sales':[200, 120, 340, 124, 243, 350]}

In [78]:
df1 =pd.DataFrame(data)

In [79]:
df1

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [38]:
df1.groupby('Company')[['Sales']].mean().loc['GOOG'].describe()

count      1.0
mean     160.0
std        NaN
min      160.0
25%      160.0
50%      160.0
75%      160.0
max      160.0
Name: GOOG, dtype: float64

In [39]:
df2 = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df2.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [41]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    4 non-null      int64 
 1   col2    4 non-null      int64 
 2   col3    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes


In [42]:
df2.col2.unique()

array([444, 555, 666], dtype=int64)

## df2

In [45]:
df2[(df2['col1']>2)&(df2['col2']==444)]

col1  col2 col3
3     4   444  xyz

In [46]:
df2.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [50]:
df2['col2'].sort_values()

0    444
3    444
1    555
2    666
Name: col2, dtype: int64

In [51]:
df3 = pd.DataFrame({'col1':[1, 2, 3, np.nan],
                   'col2':[np.nan, 555, 666, 444],
                   'col3':['abc', 'def', 'ghi', 'xyz']})
df3.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [52]:
df3.dropna(how='all')

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [53]:
df3.dropna(how='any')

col1   col2 col3
1   2.0  555.0  def
2   3.0  666.0  ghi

In [54]:
df3.dropna(axis=1,how='any')

col3
0  abc
1  def
2  ghi
3  xyz

In [56]:
df3['col2'].fillna(df3.col2.mean())

0    555.0
1    555.0
2    666.0
3    444.0
Name: col2, dtype: float64

In [57]:
my_map = {"GOOG": "GOO", "MSFT": "MIC", "FB":"FACE"}

In [58]:
df1['Company'] = df1['Company'].map(my_map)

In [77]:
df1

Company   Person                                              Sales
0  GOOGLE      Sam  KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK...
1  GOOGLE  Charlie  KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK...
2     MIC      Amy  KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK...
3     MIC  Vanessa  KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK...
4    FACE     Carl  KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK...
5    FACE    Sarah  KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK...

In [80]:
df1['Sales'] =df1['Sales'].map(lambda x:x*1000)

In [81]:
df1

Company   Person   Sales
0    GOOG      Sam  200000
1    GOOG  Charlie  120000
2    MSFT      Amy  340000
3    MSFT  Vanessa  124000
4      FB     Carl  243000
5      FB    Sarah  350000

In [63]:
df1['Company'] = df1['Company'].replace(to_replace='GOO',value='GOOGLE')

In [83]:
df1['Sales']=df1['Sales'].astype('str')

In [84]:
df1['Sales']=df1['Sales'].map(lambda x:x[:-3]+'K')

In [74]:
df1

Company   Person Sales
0  GOOGLE      Sam     K
1  GOOGLE  Charlie     K
2     MIC      Amy     K
3     MIC  Vanessa     K
4    FACE     Carl     K
5    FACE    Sarah     K

In [85]:
df4 = pd.DataFrame({'groups': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'var1': [10,23,33,22,11,99],
                   'var2': [100,253,333,262,111,969]})
df4

groups  var1  var2
0      A    10   100
1      B    23   253
2      C    33   333
3      A    22   262
4      B    11   111
5      C    99   969

In [87]:
df4.groupby('groups').mean().T

groups    A    B    C
var1     16   17   66
var2    181  182  651

In [92]:
df4.groupby('groups').aggregate([np.min,np.median,np.max])

var1             var2            
       amin median amax amin median amax
groups                                  
A        10     16   22  100    181  262
B        11     17   23  111    182  253
C        33     66   99  333    651  969

In [91]:
df4.groupby('groups').agg({'var1':'mean','var2':'max'})

var1  var2
groups            
A         16   262
B         17   253
C         66   969

In [93]:
df4

groups  var1  var2
0      A    10   100
1      B    23   253
2      C    33   333
3      A    22   262
4      B    11   111
5      C    99   969

In [97]:
df4.apply(np.sum)

groups    ABCABC
var1         198
var2        2028
dtype: object

In [98]:
titanic = sns.load_dataset('titanic')

In [99]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [105]:
titanic.groupby(['sex','class'])[['survived']].mean()

survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [107]:
titanic.columns.value_counts()

adult_male     1
alone          1
pclass         1
embarked       1
fare           1
deck           1
survived       1
parch          1
who            1
alive          1
sex            1
age            1
sibsp          1
class          1
embark_town    1
dtype: int64

In [116]:
l=[[1,2,3],[4,5,6],[7,8,9]]

In [117]:
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
li=[]